### PR TITLE
New commands and signals

### PR DESCRIPTION
**Pull request by pdonadeo**
In this bunch of commits you will find:
 * 3 missing commands: **`GET_BINDING_MODES`**, **`GET_CONFIG`** and **`SEND_TICK`**
 * `get_config` has a simplified interface: `val get_config : connection -> string Lwt.t`
 * you can subscribe to the `Shutdown` and `Tick` events
 * some documentation about what happens when i3 fires `SHUTDOWN`
 * a complete `GET_TREE` reply, I added the `primary` bool, `floating_nodes` and the complete structure of the `window_properties`

### CODE REVIEW

**Comment by Armael** [comment]
Thanks. Could you rebase your branch on top of current master? Unless I'm mistaking I see commits that seem to apply to the old master.

**Comment by pdonadeo** [comment]
@Armael sorry for the delay, I'm going to try the rebase, but probably not before the weekend. Is it still OK?

**Comment by Armael** [comment]
Yeah that's completely fine, take the time that you need.

**Comment by Armael** [comment]
I'm confused, I think this was going in the good direction -- do you plan on opening an other PR?
(I only closed issue #5 because the last commit of this PR solves it).

**Comment by pdonadeo** [comment]
Just opened #6 in a cleaner way.

**Pull request closed without merging**
